name: taxi_for_you
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

#flutter build apk --no-tree-shake-icons

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.15
  flutter_svg: ^1.0.3
  json_serializable: ^6.1.4
  dartz: ^0.10.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  internet_connection_checker: ^0.0.1+3
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.13
  http: ^0.13.3
  http_parser: ^4.0.2
  get_it: ^7.2.0
  lottie: ^1.2.2
  package_info_plus: ^4.0.2
  flutter_image_compress: ^2.0.3
  image_picker: ^0.8.4+11
  carousel_slider: ^4.0.0
  easy_localization: ^3.0.1
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.1.0
  flutter_phoenix: ^1.0.0
  location_geocoder: ^1.0.5
  google_maps_flutter: ^2.3.0
  google_places_flutter: ^2.0.5
  flutter_polyline_points: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^14.6.5
  url_launcher: ^6.1.10
  geolocator: ^9.0.2
  fluttertoast: ^8.0.8
  sms_autofill: ^2.2.0
  pinput: ^2.2.12
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  equatable: ^2.0.5
  keyboard_actions: ^4.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/localization/
    - assets/fonts/arabic/
    - assets/fonts/english/
    - assets/images/

  fonts:
    - family: almarai
      fonts:
        - asset: assets/fonts/arabic/Almarai-Bold.ttf
        - asset: assets/fonts/arabic/Almarai-ExtraBold.ttf
        - asset: assets/fonts/arabic/Almarai-Light.ttf
        - asset: assets/fonts/arabic/Almarai-Regular.ttf
    - family: lato
      fonts:
        - asset: assets/fonts/english/Lato-Bold.ttf
        - asset: assets/fonts/english/Lato-Black.ttf
        - asset: assets/fonts/english/Lato-Light.ttf
        - asset: assets/fonts/english/Lato-Regular.ttf
    - family: HomeIcons
      fonts:
        - asset: assets/fonts/home-icons/HomeIcons.ttf  
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo-font/Cairo-Black.ttf
        - asset: assets/fonts/cairo-font/Cairo-Bold.ttf
        - asset: assets/fonts/cairo-font/Cairo-ExtraBold.ttf
        - asset: assets/fonts/cairo-font/Cairo-ExtraLight.ttf
        - asset: assets/fonts/cairo-font/Cairo-Light.ttf
        - asset: assets/fonts/cairo-font/Cairo-Medium.ttf
        - asset: assets/fonts/cairo-font/Cairo-Regular.ttf
        - asset: assets/fonts/cairo-font/Cairo-SemiBold.ttf     
